### ISSUE TITLE
failure to compile on a Kubuntu 12.04 

### ISSUE THREAD

**Issue by samig59** [jerryd/gtk-fortran#73]
Hi,
could you advise please on this? 

At first cmake wouldn't find gtk libraries since it seems that
Kubuntu  installs gtk material in a strange place '/usr/lib/i386-linux-gnu' where cmake does not look for it. I overcame that difficulty by adding 
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /lib/x86_64-linux-gnu)
to the CMakeLists.txt.

Now cmake proceeds without complains but once make is executed, while the progression was OK at first,  it ends as follows:

Scanning dependencies of target gio_demo
[ 62%] Building Fortran object examples/CMakeFiles/gio_demo.dir/gio_demo.f90.o
Linking Fortran executable gio_demo
CMakeFiles/gio_demo.dir/gio_demo.f90.o: In function `MAIN__':
gio_demo.f90:(.text+0x11): undefined reference to `g_file_new_for_path'
gio_demo.f90:(.text+0x30): undefined reference to `g_file_replace'
gio_demo.f90:(.text+0x1d5): undefined reference to `g_output_stream_write'
gio_demo.f90:(.text+0x226): undefined reference to `g_output_stream_close'
collect2: ld returned 1 exit status
make[2]: *** [examples/gio_demo] Error 1
make[1]: *** [examples/CMakeFiles/gio_demo.dir/all] Error 2
make: *** [all] Error 2

Ah, I came so close! 61% was not bad. Any advise, please.

Thank you,

/Sakis

PS. I missed the previous message. Gio seems to be the terrible ghost here too! I removed the example and I was able to compile the rest to 100%. Please suggest how to compile the Gio example. Thank you!
